Updated Logo
hermit-os/hermit-rs pull request #463
Opened 2023-08-29 14:47 UTC by jounathaen

2023-08-29 14:58 UTC, mkroening requested changes
If we adapt the hermitcore/.github repo as logo source, we should also remove the `img` directory from this repo.

2023-08-29 16:28 UTC, jounathaen commented
> If we adapt the hermitcore/.github repo as logo source, we should also remove the `img` directory from this repo.

Done

2023-09-01 19:42 UTC, stlankes approved these changes

2023-09-03 15:46 UTC, mkroening approved these changes

2023-09-03 16:00 UTC, merged