extend wastime demo to support wasi32-wasi
hermit-os/hermit-rs pull request #595
Opened 2024-06-30 14:57 UTC by stlankes

To support wasi, the PR start to the "wasi_snapshot_preview1". Cuurently, only the basic functions are supported, which are needed to run the fibonacci example.

In addition, the fibonacci example is converted from a library to a common application.

2024-07-01 14:44 UTC, mkroening requested changes
This looks good to me overall! :)

2024-07-01 14:44 UTC, mkroening commented on examples/wasmtime/Cargo.toml
> +hermit-sync = { version = "0.1" }
Can't we use [`std::cell::OnceCell`](https://doc.rust-lang.org/stable/std/cell/struct.OnceCell.html) instead?

2024-07-01 14:44 UTC, mkroening commented on examples/wasmtime/src/preview1.rs
> +					let zereo: u32 = 0;
```suggestion
					let zero: u32 = 0;
```

2024-07-01 14:44 UTC, mkroening commented on examples/wasmtime/src/preview1.rs
> +					let zereo: u32 = 0;
```suggestion
					let zero: u32 = 0;
```

2024-07-01 14:44 UTC, mkroening commented on examples/wasmtime/src/main.rs
> +
Do we still need this?

```suggestion
```

2024-07-02 08:58 UTC, stlankes commented
@mkroening Merge it. I fullfil all your requests.

2024-07-02 09:35 UTC, mkroening approved these changes

2024-07-02 09:43 UTC, merged